<body>
    <header>
            <nav class="nav">
                    <div class="logo">
                        <a class="link-logo" href="home"><img class="img-logo" src="img/logojj.jpg" alt=""></a>
                    </div>
                         
                    <div class="menu">
                        <ul class="ul-nav">
                            <li class="listas-nav"><a class="link-nav" href="home"> Lista de Productos</a></li>
                            <li class="listas-nav"><a class="link-nav"  href="logout">logout</a></li>
                        </ul>
                    </div>    
                    <div class="buscador">
                     <form>
                        <input class="src" type="text" name="search" placeholder="MOTORES..." autocomplete="off" autofocus required>
                     </form>
                    </div>    
                </div>
          </nav>
     </header>   
</body>    
