<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">   <!-- Esta es una costante definida para obtener la raiz del archivo de forma dinamica -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css/style.css">
    <title>J y J Autopartes</title>    
</head>